// GENERATED by pathland-codegen — DO NOT EDIT.
// Source of truth: lib/ui/components.yaml (enum `Align`)
package pathland;

/** Typed `Align` values. Wire value is the protocol ENUM value; property `alignment` = 0x0002. */
public enum Align {
    CENTER(1),
    FILL(3),
    LEADING(0),
    TRAILING(2);

    public final int wire;
    public final int property = Constants.PROP_ALIGNMENT;

    public int wire() { return wire; }

    Align(int wire) { this.wire = wire; }
}
