// GENERATED by pathland-codegen — DO NOT EDIT.
// Source of truth: lib/ui/components.yaml (ComponentNode)
package pathland;

import java.util.ArrayList;
import java.util.List;

/** A component node (mirrors a DSL component). Constructor props are set on build. */
public final class ComponentNode implements View {
    private final int componentId;
    private final String text;
    private final List<View> children = new ArrayList<>();
    private final java.util.Map<Integer, Float> constructorProps = new java.util.LinkedHashMap<>();

    public ComponentNode(int componentId, String text, List<View> children) {
        this.componentId = componentId;
        this.text = text;
        this.children.addAll(children);
    }

    public ComponentNode setConstructorProp(int property, float value) {
        constructorProps.put(property, value);
        return this;
    }

    @Override
    public Node build() {
        Node node = new Node(0, componentId);
        if (text != null) node.string = text;
        node.properties.putAll(constructorProps);
        for (View child : children) node.children.add(child.build());
        return node;
    }
}
