// GENERATED by pathland-codegen — DO NOT EDIT.
// Source of truth: lib/ui/components.yaml (Constants)
package pathland;

/** Protocol ids and size sentinels (mirrors pathland_core::constants). */
public final class Constants {
    private Constants() {}

    // --- size sentinels (WIDTH / HEIGHT) ---
    public static final float FILL = -1f;
    public static final float HUG_CONTENT = -2f;

    // --- component ids ---
    public static final int BUTTON = 0x0004;
    public static final int COMMENT = 0x000C;
    public static final int GRID = 0x000B;
    public static final int HSTACK = 0x0001;
    public static final int IMAGE = 0x0005;
    public static final int LIST = 0x000A;
    public static final int SCROLLVIEW = 0x0009;
    public static final int SPACER = 0x0008;
    public static final int SWITCH = 0x0006;
    public static final int TEXT = 0x0003;
    public static final int TEXT_FIELD = 0x0007;
    public static final int VSTACK = 0x0002;

    // --- property ids ---
    public static final int PROP_ALIGNMENT = 0x0002;
    public static final int PROP_BACKGROUND_COLOR = 0x1001;
    public static final int PROP_BORDER_COLOR = 0x1004;
    public static final int PROP_BORDER_RADIUS = 0x1005;
    public static final int PROP_BORDER_WIDTH = 0x1003;
    public static final int PROP_CLIPS_TO_BOUNDS = 0x1010;
    public static final int PROP_COLOR = 0x100A;
    public static final int PROP_CONTENT_MARGINS = 0x0005;
    public static final int PROP_ENABLED = 0x2003;
    public static final int PROP_EVENT_LISTENERS = 0x2005;
    public static final int PROP_FONT_FAMILY = 0x1009;
    public static final int PROP_FONT_SIZE = 0x1007;
    public static final int PROP_FONT_WEIGHT = 0x1008;
    public static final int PROP_HEIGHT = 0x100C;
    public static final int PROP_LINE_LIMIT = 0x000B;
    public static final int PROP_OPACITY = 0x100D;
    public static final int PROP_PADDING = 0x1011;
    public static final int PROP_PADDING_BOTTOM = 0x1014;
    public static final int PROP_PADDING_LEFT = 0x1015;
    public static final int PROP_PADDING_RIGHT = 0x1013;
    public static final int PROP_PADDING_STYLE = 0x1006;
    public static final int PROP_PADDING_TOP = 0x1012;
    public static final int PROP_ROLE = 0x2001;
    public static final int PROP_SELECTED = 0x2004;
    public static final int PROP_SPACING = 0x0001;
    public static final int PROP_STATE = 0x2002;
    public static final int PROP_TEXT = 0x000A;
    public static final int PROP_TEXT_ALIGNMENT = 0x000C;
    public static final int PROP_TRUNCATION_MODE = 0x000D;
    public static final int PROP_VISIBLE = 0x100E;
    public static final int PROP_WIDTH = 0x100B;
    public static final int PROP_Z_INDEX = 0x100F;
}
