// GENERATED by pathland-codegen — DO NOT EDIT.
// Source of truth: lib/ui/components.yaml (DSL)
package pathland;

import java.util.Arrays;
import java.util.List;

/**
 * Static DSL entry points. Component CONSTRUCTOR properties are passed as
 * constructor args (never chainable); global modifiers chain on any view.
 */
public final class DSL {
    private DSL() {}

    /** Create a Button with the given text content. */
    public static View button(String content) {
        return new ComponentNode(Constants.BUTTON, content, java.util.Collections.emptyList());
    }

    /** Create a Comment with the given children. */
    public static View comment(View... children) {
        return new ComponentNode(Constants.COMMENT, null, Arrays.asList(children));
    }

    /** Create a Grid with the given children. */
    public static View grid(View... children) {
        return new ComponentNode(Constants.GRID, null, Arrays.asList(children));
    }

    /** Create a HStack with the given children. */
    public static View hstack(View... children) {
        return new ComponentNode(Constants.HSTACK, null, Arrays.asList(children));
    }

    /** Create a HStack with constructor properties (structural/layout — never chainable). */
    public static View hstack(Align alignment, float spacing, View... children) {
        ComponentNode node = new ComponentNode(Constants.HSTACK, null, Arrays.asList(children));
        node.setConstructorProp(Constants.PROP_ALIGNMENT, alignment.wire);
        node.setConstructorProp(Constants.PROP_SPACING, spacing);
        return node;
    }

    /** Create a Image. */
    public static View image() {
        return new ComponentNode(Constants.IMAGE, null, java.util.Collections.emptyList());
    }

    /** Create a List with the given children. */
    public static View list(View... children) {
        return new ComponentNode(Constants.LIST, null, Arrays.asList(children));
    }

    /** Create a ScrollView with the given children. */
    public static View scrollview(View... children) {
        return new ComponentNode(Constants.SCROLLVIEW, null, Arrays.asList(children));
    }

    /** Create a Spacer. */
    public static View spacer() {
        return new ComponentNode(Constants.SPACER, null, java.util.Collections.emptyList());
    }

    /** Create a Switch. */
    public static View switch_() {
        return new ComponentNode(Constants.SWITCH, null, java.util.Collections.emptyList());
    }

    /** Create a Text with the given text content. */
    public static View text(String content) {
        return new ComponentNode(Constants.TEXT, content, java.util.Collections.emptyList());
    }

    /** Create a Text with constructor properties (structural/layout — never chainable). */
    public static View text(TextAlign textalignment, int linelimit, Truncation truncationmode, String content) {
        ComponentNode node = new ComponentNode(Constants.TEXT, content, java.util.Collections.emptyList());
        node.setConstructorProp(Constants.PROP_TEXT_ALIGNMENT, textalignment.wire);
        node.setConstructorProp(Constants.PROP_LINE_LIMIT, (float) linelimit);
        node.setConstructorProp(Constants.PROP_TRUNCATION_MODE, truncationmode.wire);
        return node;
    }

    /** Create a TextField. */
    public static View text_field() {
        return new ComponentNode(Constants.TEXT_FIELD, null, java.util.Collections.emptyList());
    }

    /** Create a VStack with the given children. */
    public static View vstack(View... children) {
        return new ComponentNode(Constants.VSTACK, null, Arrays.asList(children));
    }

    /** Create a VStack with constructor properties (structural/layout — never chainable). */
    public static View vstack(Align alignment, float spacing, View... children) {
        ComponentNode node = new ComponentNode(Constants.VSTACK, null, Arrays.asList(children));
        node.setConstructorProp(Constants.PROP_ALIGNMENT, alignment.wire);
        node.setConstructorProp(Constants.PROP_SPACING, spacing);
        return node;
    }

}
