// GENERATED by pathland-codegen — DO NOT EDIT.
// Source of truth: lib/ui/components.yaml (enum `FontWeight`)
package pathland;

/** Typed `FontWeight` values. Wire value is the protocol ENUM value; property `font_weight` = 0x1008. */
public enum FontWeight {
    BOLD(4),
    LIGHT(0),
    MEDIUM(2),
    REGULAR(1),
    SEMIBOLD(3);

    public final int wire;
    public final int property = Constants.PROP_FONT_WEIGHT;

    public int wire() { return wire; }

    FontWeight(int wire) { this.wire = wire; }
}
