// GENERATED by pathland-codegen — DO NOT EDIT.
// Source of truth: lib/ui/components.yaml (enum `Justify`)
package pathland;

/** Typed `Justify` values. Wire value is the protocol ENUM value; property `justification` = 0x0003. */
public enum Justify {
    CENTER(2),
    END(1),
    SPACE_AROUND(4),
    SPACE_BETWEEN(3),
    SPACE_EVENLY(5),
    START(0);

    public final int wire;
    public final int property = Constants.PROP_JUSTIFICATION;

    public int wire() { return wire; }

    Justify(int wire) { this.wire = wire; }
}
