// GENERATED by pathland-codegen — DO NOT EDIT.
// Source of truth: lib/ui/components.yaml (Modified)
package pathland;

/**
 * A view wrapped by one or more property modifiers (innermost-first).
 * Simple modifiers use the single-property constructor; the compound
 * `frame` modifier uses the map constructor for width/height/alignment.
 */
final class Modified implements View {
    private final View inner;
    private final java.util.Map<Integer, Float> props;

    Modified(View inner, int propertyId, float value) {
        this.inner = inner;
        this.props = new java.util.LinkedHashMap<>();
        this.props.put(propertyId, value);
    }

    Modified(View inner, java.util.Map<Integer, Float> props) {
        this.inner = inner;
        this.props = props;
    }

    @Override
    public Node build() {
        Node node = inner.build();
        node.properties.putAll(props);
        return node;
    }
}
