// GENERATED by pathland-codegen — DO NOT EDIT.
// Source of truth: lib/ui/components.yaml (enum `TextAlign`)
package pathland;

/** Typed `TextAlign` values. Wire value is the protocol ENUM value; property `text_alignment` = 0x000C. */
public enum TextAlign {
    CENTER(1),
    LEADING(0),
    TRAILING(2);

    public final int wire;
    public final int property = Constants.PROP_TEXT_ALIGNMENT;

    public int wire() { return wire; }

    TextAlign(int wire) { this.wire = wire; }
}
