// GENERATED by pathland-codegen — DO NOT EDIT.
// Source of truth: lib/ui/components.yaml (enum `Truncation`)
package pathland;

/** Typed `Truncation` values. Wire value is the protocol ENUM value; property `truncation_mode` = 0x000D. */
public enum Truncation {
    HEAD(0),
    MIDDLE(1),
    NONE(3),
    TAIL(2);

    public final int wire;
    public final int property = Constants.PROP_TRUNCATION_MODE;

    public int wire() { return wire; }

    Truncation(int wire) { this.wire = wire; }
}
