// GENERATED by pathland-codegen — DO NOT EDIT.
// Source of truth: lib/ui/components.yaml (View)
package pathland;

/**
 * A composable view. Implementations build a {@link Node} subtree.
 *
 * Global modifiers are chainable on any view. The compound `frame` modifier
 * sizes a view (FILL/HUG_CONTENT sentinels) and optionally aligns it.
 */
public interface View {
    Node build();

    default View padding(float value) {
        return new Modified(this, Constants.PROP_PADDING, value);
    }

    default View color(int rgba) {
        return new Modified(this, Constants.PROP_COLOR, Float.intBitsToFloat(rgba));
    }

    default View background_color(int rgba) {
        return new Modified(this, Constants.PROP_BACKGROUND_COLOR, Float.intBitsToFloat(rgba));
    }

    default View opacity(float value) {
        return new Modified(this, Constants.PROP_OPACITY, value);
    }

    default View border_width(float value) {
        return new Modified(this, Constants.PROP_BORDER_WIDTH, value);
    }

    default View border_color(int rgba) {
        return new Modified(this, Constants.PROP_BORDER_COLOR, Float.intBitsToFloat(rgba));
    }

    default View border_radius(float value) {
        return new Modified(this, Constants.PROP_BORDER_RADIUS, value);
    }

    default View font_size(float value) {
        return new Modified(this, Constants.PROP_FONT_SIZE, value);
    }

    default View font_weight(FontWeight value) {
        return new Modified(this, Constants.PROP_FONT_WEIGHT, value.wire);
    }

    default View visible(boolean value) {
        return new Modified(this, Constants.PROP_VISIBLE, value ? 1f : 0f);
    }

    default View z_index(float value) {
        return new Modified(this, Constants.PROP_Z_INDEX, value);
    }

    default View clips_to_bounds(boolean value) {
        return new Modified(this, Constants.PROP_CLIPS_TO_BOUNDS, value ? 1f : 0f);
    }

    /**
     * Compound sizing modifier. Pass {@link Constants#FILL} / {@link Constants#HUG_CONTENT}
     * for a fixed axis, or {@code Float.NaN} to leave it to the native renderer.
     *
     * @param width     width hint (FILL / HUG_CONTENT / NaN for unset)
     * @param height    height hint (FILL / HUG_CONTENT / NaN for unset)
     * @param alignment cross-axis alignment, or null for unset
     */
    default View frame(float width, float height, Align alignment) {
        java.util.Map<Integer, Float> props = new java.util.LinkedHashMap<>();
        if (!Float.isNaN(width)) props.put(Constants.PROP_WIDTH, width);
        if (!Float.isNaN(height)) props.put(Constants.PROP_HEIGHT, height);
        if (alignment != null) props.put(Constants.PROP_ALIGNMENT, (float) alignment.wire);
        return new Modified(this, props);
    }
}
