[workspace]
resolver = "2"
members = [
    "crates/pathland-core",
    "crates/pathland-engine",
    "crates/pathland-view",
    "crates/pathland-core-transport",
    "crates/pathland-view-native",
    "crates/pathland-render-gtk",
    "crates/pathland-render-gtk-demo",
    "crates/pathland-codegen",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.85"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
