package com.pathland.view.state;

import com.pathland.view.signal.EffectRef;
import com.pathland.view.signal.Signals;
import com.pathland.view.signal.WritableSignal;

import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

/**
 * A per-session handle that connects {@link State} fields to a {@link StateStore}.
 *
 * <p>{@link #signal(String, Object)} creates a signal that auto-loads its persisted value
 * as the initial value and auto-saves on every change, keyed {@code "name:scope"}. Signals
 * are memoized by name, so repeat calls return the same instance. {@link #connect(Object)}
 * wires a view's {@code @Persisted} fields (and, recursively, its nested view fields)
 * through the binder generated by {@code pathland-view-processor}.
 */
public final class PersistentState implements AutoCloseable {

    /** Generated binder methods, cached per view class. */
    private static final Map<Class<?>, Method> BINDERS = new ConcurrentHashMap<>();
    private static final Set<Class<?>> NO_BINDER = ConcurrentHashMap.newKeySet();

    private final StateStore store;
    private final String scope;
    private final Map<String, WritableSignal<?>> signals = new HashMap<>();
    private final List<EffectRef> persistEffects = new ArrayList<>();

    public PersistentState(StateStore store, String scope) {
        this.store = store;
        this.scope = scope;
    }

    /**
     * Create (or return the memoized) signal named {@code name}, auto-loading its
     * persisted value as the initial value and auto-saving on change.
     */
    @SuppressWarnings("unchecked")
    public <T> WritableSignal<T> signal(String name, T initial) {
        WritableSignal<T> existing = (WritableSignal<T>) signals.get(name);
        if (existing != null) {
            return existing;
        }
        String key = scoped(name);
        Class<T> clazz = (Class<T>) initial.getClass();
        WritableSignal<T> signal = Signals.signal(name, store.load(key, clazz).orElse(initial));
        signals.put(name, signal);
        persistEffects.add(Signals.effect(() -> {
            try {
                store.save(key, signal.get());
            } catch (RuntimeException e) {
                // Persistence is best-effort for a UI component.
            }
        }));
        return signal;
    }

    private String scoped(String name) {
        return scope == null || scope.isEmpty() ? name : name + ":" + scope;
    }

    /**
     * Wire every {@code @Persisted} field of {@code view} — and, recursively, of its
     * nested view fields — through the generated {@code <Class>_StateBinder}. Views
     * without generated binders (e.g. library primitives) are a no-op.
     */
    public void connect(Object view) {
        Class<?> type = view.getClass();
        if (NO_BINDER.contains(type)) {
            return;
        }
        Method binder = BINDERS.get(type);
        if (binder == null) {
            try {
                Class<?> binderClass = Class.forName(type.getName() + "_StateBinder");
                binder = binderClass.getMethod("connect", type, PersistentState.class);
                BINDERS.put(type, binder);
            } catch (ClassNotFoundException e) {
                NO_BINDER.add(type);
                return;
            } catch (ReflectiveOperationException e) {
                throw new IllegalStateException("state binder for " + type + " is unusable", e);
            }
        }
        try {
            binder.invoke(null, view, this);
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException("state connect failed for " + type, e);
        }
    }

    @Override
    public void close() {
        for (EffectRef effect : persistEffects) {
            effect.destroy();
        }
        persistEffects.clear();
        signals.clear();
    }
}