package com.pathland.processor;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.PackageElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Generates a {@code <View>_StateBinder} per {@code View} implementation that declares
 * {@code State} fields and/or nested view fields. Fields are detected by type (no
 * annotation): a {@code com.pathland.view.state.State} field is a persisted signal
 * (bound by field name — an explicit key lives on the {@code State} constructor), and a
 * {@code View} field is a nested view to recurse into.
 *
 * <p>Generated binders are discovered at runtime by {@code PersistentState.connect} via
 * the {@code <Class>_StateBinder} naming convention.
 */
@SupportedAnnotationTypes("*")
public final class PersistedProcessor extends AbstractProcessor {

    private final Set<String> generated = new HashSet<>();

    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latestSupported();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (roundEnv.processingOver()) {
            return false;
        }
        Elements elements = processingEnv.getElementUtils();
        Types types = processingEnv.getTypeUtils();
        TypeElement viewType = elements.getTypeElement("com.pathland.view.View");
        TypeElement stateType = elements.getTypeElement("com.pathland.view.state.State");
        if (viewType == null || stateType == null) {
            return false; // pathland-view not on the processing classpath
        }
        TypeMirror viewErasure = types.erasure(viewType.asType());
        TypeMirror stateErasure = types.erasure(stateType.asType());

        for (Element root : roundEnv.getRootElements()) {
            if (!(root instanceof TypeElement type) || type.getKind() != ElementKind.CLASS) {
                continue;
            }
            if (!types.isAssignable(types.erasure(type.asType()), viewErasure)) {
                continue;
            }
            List<String> persisted = new ArrayList<>(); // field names
            List<String> nested = new ArrayList<>();
            for (Element enclosed : type.getEnclosedElements()) {
                if (enclosed.getKind() != ElementKind.FIELD) {
                    continue;
                }
                VariableElement field = (VariableElement) enclosed;
                TypeMirror fieldType = types.erasure(field.asType());
                if (types.isAssignable(fieldType, stateErasure)) {
                    persisted.add(field.getSimpleName().toString());
                } else if (types.isAssignable(fieldType, viewErasure)) {
                    nested.add(field.getSimpleName().toString());
                }
            }
            if (persisted.isEmpty() && nested.isEmpty()) {
                continue;
            }
            generateBinder(elements, type, persisted, nested);
        }
        return false;
    }

    private void generateBinder(Elements elements, TypeElement type, List<String> persisted, List<String> nested) {
        PackageElement pkg = elements.getPackageOf(type);
        String pkgName = pkg.getQualifiedName().toString();
        String simple = type.getSimpleName().toString();
        String binderName = simple + "_StateBinder";
        String fq = pkgName.isEmpty() ? binderName : pkgName + "." + binderName;
        if (!generated.add(fq)) {
            return;
        }

        StringBuilder sb = new StringBuilder();
        if (!pkgName.isEmpty()) {
            sb.append("package ").append(pkgName).append(";\n\n");
        }
        sb.append("import com.pathland.view.state.PersistentState;\n\n");
        sb.append("/** Generated by pathland-view-processor — wires State fields. */\n");
        sb.append("public final class ").append(binderName).append(" {\n");
        sb.append("    public static void connect(").append(simple).append(" v, PersistentState s) {\n");
        for (String field : persisted) {
            sb.append("        v.").append(field).append(".bind(s, \"").append(field).append("\");\n");
        }
        for (String n : nested) {
            sb.append("        s.connect(v.").append(n).append(");\n");
        }
        sb.append("    }\n");
        sb.append("}\n");

        try {
            JavaFileObject file = processingEnv.getFiler().createSourceFile(fq, type);
            try (Writer w = file.openWriter()) {
                w.write(sb.toString());
            }
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "failed to write " + fq + ": " + e.getMessage());
        }
    }
}
